name: CI/CD for Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t my-flask-app .

    - name: Deploy to production
      run: |
        docker tag my-flask-app my-docker-registry/my-flask-app:latest
        docker push my-docker-registry/my-flask-app:latest
